spring.application.name=fitnesslog

## logging
logging.level.org.springframework.data.mongodb.core=DEBUG

## server
server.port=8085

## jwt
jwt.secret=cpsc449-fitnesslog-secret-key-must-be-at-least-256-bits-long!
jwt.expiration=84000000